@startuml Use Case Diagram

left to right direction
actor "User" as user

rectangle "Use Cases" {
    usecase "manage account" as manage_account
    usecase "search user" as search_user
    usecase "manage chat" as manage_chat
    usecase "manage message" as manage_message
    usecase "modify password" as modify_password
}
user --> manage_account
user --> search_user
user --> manage_chat
user --> manage_message
user --> modify_password
@enduml