@startuml User Domain
!include meta/Domain.Analysis.metamodel.iuml

$aggregate(User) {
    $aggregate_root(User) {
        + id: Guid
        + updateName(Name)
        + updateSurname(Name)
        + updateUsername(Name)
    }

    $value(Name) {
        + value: String
    }

    $value(Surname) {
        + value: String
    }

    $value(Username) {
        + value: String
    }

    $value(Email) {
        + value: String
    }
    
    Name -o User
    Surname -o User
    Username -o User
    Email -o User
}
@enduml