@startuml User Domain
!include meta/Domain.Analysis.metamodel.iuml

$aggregate(User) {
    $aggregate_root(User) {
        + id: Guid
        + name: String
        + email: String
        + password: String
        + creationTime: DateTime
        + lastLoginTime: Option[DateTime]
        + editEmail(String)
        + editPassword(String)
        + editName(String)
    }
}

$service(ChatService) {
    + createUser(name: String, email: String, password: String): User
    + editUser(userId: Guid, email: String): User
    + editPassword(userId: Guid, password: String): User
    + editName(userId: Guid, name: String): User
    + getUsers(chatId: Guid, pageIndex: Number, PageDimension: Number)
}

@enduml