version: 3

mssql: &mssql
  image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
  environment:
    MSSQL_PID: Developer
    ACCEPT_EULA: 'Y'
    SA_PASSWORD: ${PASSWORD:?password not set}

services:
  authdb:
    <<: *mssql
    ports:
      - 8005:1433
    volumes:
      - authdb_volume:/var/opt/mssql
  userdb:
    <<: *mssql
    ports:
      - 8006:1433
    volumes:
      - userdb_volume:/var/opt/mssql
  chatdb:
    <<: *mssql
    ports:
      - 8007:1433
    volumes:
      - chatdb_volume:/var/opt/mssql
  rabbitmq: 
    image: rabbitmq:3.9
    ports:
      -
    volumes:
      - 
  redis:
    image: redis:6.2
    ports:
      -
    volumes:
      -
