@startuml PrivateChat Context
!include meta/domain-analysis.metamodel.iuml
!include chat-subdomain.puml

$aggregate(PrivateMessage) {
    $aggregate_root(PrivateMessage) {
        + id: Guid
        + chatId: Guid
        + sendTime: DateTime
        + lastEditTime: Option[DateTime]
        + senderId: Guid
        + viewed: Bool
        + editText(newText: String): void
        + setViewed(): Void
    }
    
    $value(MessageText) {
        + text: String
    }

    MessageText -o PrivateMessage
}

$aggregate(PrivateChat) {
    $aggregate_root(PrivateChat) extends Chat {
        + partecipantId: Guid
    }
}

$service(ChatService) {
    + createChat(participants: List[Guid]): Chat
    + getLastUsedChats(userId: Guid): List[Chat]
    + getChat(userId: Guid, chatId: Guid) : Chat
    + sendMessage(chatId: Guid, text: String, userId: Guid): Message
    + editMessage(messageId: Guid, text: String, userId: Guid): Message
    + deleteMessage(messageId: Guid, userId: Guid): Message
    + getLastSentMessages(userId: Guid): List[Message]
}

User "1" <.left. "0..*" PrivateMessage: sender
PrivateMessage "0..*" --* "1" Chat: isSentOn
User "1" <.. "0..*" PrivateChat: partecipant

@enduml