@startuml PrivateChat Subdomain
!include meta/Domain.Analysis.metamodel.iuml
!include Chat/Chat.Domain.puml

$aggregate(PrivateMessage) {
    $aggregate_root(PrivateMessage) extends Message{
        + viewed: Bool
        + setViewed(): Void
    }
}

$aggregate(PrivateChat) {
    $aggregate_root(PrivateChat) extends Chat {
        + partecipant: Guid
    }
}

$service(ChatService) {
    + createChat(participants: List[Guid]): Chat
    + sendMessage(chatId: Guid, text: String, userId: Guid): Message
    + editMessage(messageId: Guid, text: String, userId: Guid): Message
    + deleteMessage(messageId: Guid, userId: Guid): Message
}

User "1" <.. "0..*" PrivateChat: partecipant

@enduml