@startuml PrivateChat Subdomain
!include meta/Domain.Analysis.metamodel.iuml
!include Chat/Chat.Domain.puml


$aggregate(Message) {
    $aggregate_root(Message) {
        + id: Guid
        + chatId: Guid
        + text: String
        + sendTime: DateTime
        + lastEditTime: Option[DateTime]
        + sender: Guid
        + editText(newText: String): void 
    }
}

$aggregate(User) {
    $entity(User) {
        + id: Guid
    }
}

$aggregate(PrivateChat) {
    $aggregate_root(PrivateChat) extends Chat {
        + partecipant: Guid
    }
}

$service(ChatService) {
    + createChat(participants: List[Guid]): Chat
    + sendMessage(chatId: Guid, text: String, userId: Guid): Message
    + editMessage(messageId: Guid, text: String, userId: Guid): Message
    + deleteMessage(messageId: Guid, userId: Guid): Message
}

Message "0..*" --* "1" Chat: isSentOn
User "1" <.left. "0..*" Message: sender
User "1" <.. "0..*" Chat: owner
User "1" <.. "0..*" PrivateChat: partecipant


@enduml