@startuml User Domain
!include meta/Domain.Analysis.metamodel.iuml

$aggregate(User) {
    $aggregate_root(User) {
        + id: Guid
        + name: String
        + email: String
        + password: String
        + creationTime: DateTime
        + lastLoginTime: Option[DateTime]
        + editEmail(String)
        + editPassword(String)
        + editName(String)
    }
}
@enduml