# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CI

on:
  push:
    branches:
      - "**"
    paths:
      - "frontend/microchat-frontend/**"
      - ".github/workflows/frontend*.yml"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Build & Test Angular Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: frontend/microchat-frontend
        run: npm ci
      - name: Build
        working-directory: frontend/microchat-frontend
        run: npm run-script build
      #- name: Test
      #  working-directory: frontend/microchat-frontend
      #  run: npm run-script test
