# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CI

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/*"
      - "frontend/microchat-frontend"
  workflow_call:
    inputs:
      app-publish-dir:
        required: true
        type: string

env:
  path: frontend/microchat-frontend
  human-friendly-name: static_site
  artifact-name: build-artifacts
  output-dir: ./dist

jobs:
  build:
    name: Build & Test Angular Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ${{ env.path }}
        run: npm ci
      - name: Build
        working-directory: ${{ env.path }}
        run: npm run-script build
      - name: Test
        working-directory: ${{ env.path }}
        run: npm run-script test-prod
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.human-friendly-name }}
          path: ${{ env.output-dir }}