name: Mirror Repository

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  delete:

jobs:
  gitlab:
    name: Mirror repository on GitLab
    runs-on: ubuntu-latest
    environment: gitlab-mirror
    steps:
      - uses: EasyDesk/action-semver-checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:${{ secrets.GITLAB_REPOSITORY }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
